export const testTableData = {
  prev: false,
  next: true,
  data: [
    {
      name: 'Nonprofit 1',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 0,
      isSent: false,
    },
    {
      name: 'Nonprofit 2',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 1,
      isSent: false,
    },
    {
      name: 'Nonprofit 3',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 2,
      isSent: false,
    },
    {
      name: 'Nonprofit 4',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 3,
      isSent: false,
    },
    {
      name: 'Nonprofit 5',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 4,
      isSent: false,
    },
    {
      name: 'Nonprofit 6',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 5,
      isSent: false,
    },
    {
      name: 'Nonprofit 7',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 6,
      isSent: false,
    },
    {
      name: 'Nonprofit 8',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 7,
      isSent: false,
    },
    {
      name: 'Nonprofit 9',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 8,
      isSent: false,
    },
    {
      name: 'Nonprofit 10',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 9,
      isSent: false,
    },
  ],
};

export const testTableDataAlt = {
  prev: true,
  next: false,
  data: [
    {
      name: 'Nonprofit 11',
      addressLine1: '321 Street Ln.',
      city: 'Asheville',
      state: 'NC',
      zipcode: '28806',
      amount: 25000,
      id: 10,
      isSent: false,
    },
    {
      name: 'Nonprofit 12',
      addressLine1: '321 Street Ln.',
      city: 'Asheville',
      state: 'NC',
      zipcode: '28806',
      amount: 25000,
      id: 11,
      isSent: false,
    },
    {
      name: 'Nonprofit 13',
      addressLine1: '321 Street Ln.',
      city: 'Asheville',
      state: 'NC',
      zipcode: '28806',
      amount: 25000,
      id: 12,
      isSent: false,
    },
    {
      name: 'Nonprofit 14',
      addressLine1: '321 Street Ln.',
      city: 'Asheville',
      state: 'NC',
      zipcode: '28806',
      amount: 25000,
      id: 13,
      isSent: false,
    },
    {
      name: 'Nonprofit 15',
      addressLine1: '321 Street Ln.',
      city: 'Asheville',
      state: 'NC',
      zipcode: '28806',
      amount: 25000,
      id: 14,
      isSent: false,
    },
    {
      name: 'Nonprofit 16',
      addressLine1: '321 Street Ln.',
      city: 'Asheville',
      state: 'NC',
      zipcode: '28806',
      amount: 25000,
      id: 15,
      isSent: false,
    },
    {
      name: 'Nonprofit 17',
      addressLine1: '321 Street Ln.',
      city: 'Asheville',
      state: 'NC',
      zipcode: '28806',
      amount: 25000,
      id: 16,
      isSent: false,
    },
    {
      name: 'Nonprofit 18',
      addressLine1: '321 Street Ln.',
      city: 'Asheville',
      state: 'NC',
      zipcode: '28806',
      amount: 25000,
      id: 17,
      isSent: false,
    },
    {
      name: 'Nonprofit 19',
      addressLine1: '',
      city: '',
      state: '',
      zipcode: '',
      amount: 25000,
      id: 18,
      isSent: false,
    },
    {
      name: 'Nonprofit 20',
      addressLine1: '321 Street Ln.',
      city: 'Asheville',
      state: 'NC',
      zipcode: '28806',
      amount: 25000,
      id: 19,
      isSent: false,
    },
  ],
};

export const jestTableData = {
  prev: false,
  next: true,
  data: [
    {
      name: 'Nonprofit 1',
      addressLine1: '123 Street St.',
      city: 'New York',
      state: 'NY',
      zipcode: '12986',
      amount: 10000,
      id: 0,
      isSent: true,
    },
  ],
};
