export const testTableData = [
  {
    name: 'Nonprofit 1',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 0,
    isSent: false,
  },
  {
    name: 'Nonprofit 2',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 1,
    isSent: false,
  },
  {
    name: 'Nonprofit 3',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 2,
    isSent: false,
  },
  {
    name: 'Nonprofit 4',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 3,
    isSent: false,
  },
  {
    name: 'Nonprofit 5',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 4,
    isSent: false,
  },
  {
    name: 'Nonprofit 6',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 5,
    isSent: false,
  },
  {
    name: 'Nonprofit 7',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 6,
    isSent: false,
  },
  {
    name: 'Nonprofit 8',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 7,
    isSent: false,
  },
  {
    name: 'Nonprofit 9',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 8,
    isSent: false,
  },
  {
    name: 'Nonprofit 10',
    addressLine1: '123 Street St.',
    city: 'New York',
    state: 'NY',
    zipcode: '12986',
    amount: 10000,
    id: 9,
    isSent: false,
  },
];
